/*
 * This file has been automatically generated by Soupply and released un the MIT license.
 */
module soupply.protocol.java338.packet;

import packetmaker;

alias Java338Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
