/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java393.packet;

import packetmaker;

alias Java393Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
