/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java335.protocol;

public import soupply.java335.protocol.clientbound;
public import soupply.java335.protocol.login;
public import soupply.java335.protocol.serverbound;
public import soupply.java335.protocol.status;
