/*
 * This file has been automatically generated by Soupply and released un the MIT license.
 */
module soupply.protocol.java315.packet;

import packetmaker;

alias Java315Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
