/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 * Generated from data/java393.xml
 */
module soupply.java393.protocol.login_clientbound;

static import std.conv;
import std.typetuple : TypeTuple;
import xpacket;

import soupply.util;
import soupply.java393.metadata : Metadata;
import soupply.java393.packet : Java393Packet;

static import soupply.java393.types;

alias Packets = TypeTuple!(Disconnect, EncryptionRequest, LoginSuccess, SetCompression, PluginRequest);

class Disconnect : Java393Packet
{

    enum uint ID = 0;

    enum bool CLIENTBOUND = true;
    enum bool SERVERBOUND = false;

    enum string[] __fields = ["reason"];

    string reason;

    this() pure nothrow @safe @nogc {}

    this(string reason) pure nothrow @safe @nogc
    {
        this.reason = reason;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        Disconnect ret = new Disconnect();
        ret.decode(buffer);
        return ret;
    }

    override string toString()
    {
        return "Disconnect(reason: " ~ std.conv.to!string(this.reason) ~ ")";
    }

}

class EncryptionRequest : Java393Packet
{

    enum uint ID = 1;

    enum bool CLIENTBOUND = true;
    enum bool SERVERBOUND = false;

    enum string[] __fields = ["serverId", "publicKey", "verifyToken"];

    string serverId;
    ubyte[] publicKey;
    ubyte[] verifyToken;

    this() pure nothrow @safe @nogc {}

    this(string serverId, ubyte[] publicKey=(ubyte[]).init, ubyte[] verifyToken=(ubyte[]).init) pure nothrow @safe @nogc
    {
        this.serverId = serverId;
        this.publicKey = publicKey;
        this.verifyToken = verifyToken;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        EncryptionRequest ret = new EncryptionRequest();
        ret.decode(buffer);
        return ret;
    }

    override string toString()
    {
        return "EncryptionRequest(serverId: " ~ std.conv.to!string(this.serverId) ~ ", publicKey: " ~ std.conv.to!string(this.publicKey) ~ ", verifyToken: " ~ std.conv.to!string(this.verifyToken) ~ ")";
    }

}

class LoginSuccess : Java393Packet
{

    enum uint ID = 2;

    enum bool CLIENTBOUND = true;
    enum bool SERVERBOUND = false;

    enum string[] __fields = ["uuid", "username"];

    string uuid;
    string username;

    this() pure nothrow @safe @nogc {}

    this(string uuid, string username=string.init) pure nothrow @safe @nogc
    {
        this.uuid = uuid;
        this.username = username;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        LoginSuccess ret = new LoginSuccess();
        ret.decode(buffer);
        return ret;
    }

    override string toString()
    {
        return "LoginSuccess(uuid: " ~ std.conv.to!string(this.uuid) ~ ", username: " ~ std.conv.to!string(this.username) ~ ")";
    }

}

class SetCompression : Java393Packet
{

    enum uint ID = 3;

    enum bool CLIENTBOUND = true;
    enum bool SERVERBOUND = false;

    enum string[] __fields = ["thresold"];

    @Var uint thresold;

    this() pure nothrow @safe @nogc {}

    this(uint thresold) pure nothrow @safe @nogc
    {
        this.thresold = thresold;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        SetCompression ret = new SetCompression();
        ret.decode(buffer);
        return ret;
    }

    override string toString()
    {
        return "SetCompression(thresold: " ~ std.conv.to!string(this.thresold) ~ ")";
    }

}

class PluginRequest : Java393Packet
{

    enum uint ID = 4;

    enum bool CLIENTBOUND = true;
    enum bool SERVERBOUND = false;

    enum string[] __fields = ["messageId", "channel", "data"];

    @Var uint messageId;
    string channel;
    @NoLength ubyte[] data;

    this() pure nothrow @safe @nogc {}

    this(uint messageId, string channel=string.init, ubyte[] data=(ubyte[]).init) pure nothrow @safe @nogc
    {
        this.messageId = messageId;
        this.channel = channel;
        this.data = data;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        PluginRequest ret = new PluginRequest();
        ret.decode(buffer);
        return ret;
    }

    override string toString()
    {
        return "PluginRequest(messageId: " ~ std.conv.to!string(this.messageId) ~ ", channel: " ~ std.conv.to!string(this.channel) ~ ", data: " ~ std.conv.to!string(this.data) ~ ")";
    }

}
