/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java393.protocol;

public import soupply.java393.protocol.login_clientbound;
public import soupply.java393.protocol.login_serverbound;
public import soupply.java393.protocol.play_clientbound;
public import soupply.java393.protocol.play_serverbound;
public import soupply.java393.protocol.status;
