/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 * Generated from data/java393.xml
 */
module soupply.java393.protocol.play_serverbound;

static import std.conv;
import std.typetuple : TypeTuple;
import packetmaker;

import soupply.util;
import soupply.java393.metadata : Metadata;
import soupply.java393.packet : Java393Packet;

static import soupply.java393.types;

alias Packets = TypeTuple!(TeleportConfirm, QueryBlockNbt, ChatMessage, ClientStatus, ClientSettings, TabComplete, ConfirmTransaction, EnchantItem, ClickWindow, CloseWindow, PluginMessage, EditBook, QueryEntityNbt, UseEntity, KeepAlive, Player, PlayerPosition, PlayerPositionAndLook, PlayerLook, VehicleMove, SteerBoat, PickItem, CraftRecipeRequest, PlayerAbilities, PlayerDigging, EntityAction, SteerVehicle, RecipeBookData, NameItem, ResourcePackStatus, AdvencementTab, SelectTrade, SetBeaconEffect, HeldItemChange, UpdateCommandBlock, UpdateCommandBlockMinecart, CreativeInventoryAction, UpdateStructureBlock, UpdateSign, Animation, Spectate, PlayerBlockPlacement, UseItem);

class TeleportConfirm : Java393Packet
{

    enum uint ID = 0;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["teleportId"];

    @Var uint teleportId;

    this() pure nothrow @safe @nogc {}

    this(uint teleportId) pure nothrow @safe @nogc
    {
        this.teleportId = teleportId;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        TeleportConfirm ret = new TeleportConfirm();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "TeleportConfirm(teleportId: " ~ std.conv.to!string(this.teleportId) ~ ")";
    }

}

class QueryBlockNbt : Java393Packet
{

    enum uint ID = 1;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["transationId", "location"];

    @Var uint transationId;
    soupply.java393.types.Position location;

    this() pure nothrow @safe @nogc {}

    this(uint transationId, soupply.java393.types.Position location=soupply.java393.types.Position.init) pure nothrow @safe @nogc
    {
        this.transationId = transationId;
        this.location = location;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        QueryBlockNbt ret = new QueryBlockNbt();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "QueryBlockNbt(transationId: " ~ std.conv.to!string(this.transationId) ~ ", location: " ~ std.conv.to!string(this.location) ~ ")";
    }

}

class ChatMessage : Java393Packet
{

    enum uint ID = 2;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["text"];

    string text;

    this() pure nothrow @safe @nogc {}

    this(string text) pure nothrow @safe @nogc
    {
        this.text = text;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        ChatMessage ret = new ChatMessage();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "ChatMessage(text: " ~ std.conv.to!string(this.text) ~ ")";
    }

}

class ClientStatus : Java393Packet
{

    enum uint ID = 3;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // action
    enum uint RESPAWN = 0;
    enum uint REQUEST_STATS = 1;

    enum string[] __fields = ["action"];

    @Var uint action;

    this() pure nothrow @safe @nogc {}

    this(uint action) pure nothrow @safe @nogc
    {
        this.action = action;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        ClientStatus ret = new ClientStatus();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "ClientStatus(action: " ~ std.conv.to!string(this.action) ~ ")";
    }

}

class ClientSettings : Java393Packet
{

    enum uint ID = 4;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // chat mode
    enum uint ENABLED = 0;
    enum uint COMMANDS_ONLY = 1;
    enum uint DISABLED = 2;

    // displayed skin parts
    enum ubyte CAPE = 1;
    enum ubyte JACKET = 2;
    enum ubyte LEFT_SLEEVE = 4;
    enum ubyte RIGHT_SLEEVE = 8;
    enum ubyte LEFT_PANTS = 16;
    enum ubyte RIGHT_PANTS = 32;
    enum ubyte HAT = 64;

    // main hand
    enum ubyte RIGHT = 0;
    enum ubyte LEFT = 1;

    enum string[] __fields = ["language", "viewDistance", "chatMode", "chatColors", "displayedSkinParts", "mainHand"];

    string language;
    ubyte viewDistance;
    @Var uint chatMode;
    bool chatColors;
    ubyte displayedSkinParts;
    ubyte mainHand;

    this() pure nothrow @safe @nogc {}

    this(string language, ubyte viewDistance=ubyte.init, uint chatMode=uint.init, bool chatColors=bool.init, ubyte displayedSkinParts=ubyte.init, ubyte mainHand=ubyte.init) pure nothrow @safe @nogc
    {
        this.language = language;
        this.viewDistance = viewDistance;
        this.chatMode = chatMode;
        this.chatColors = chatColors;
        this.displayedSkinParts = displayedSkinParts;
        this.mainHand = mainHand;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        ClientSettings ret = new ClientSettings();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "ClientSettings(language: " ~ std.conv.to!string(this.language) ~ ", viewDistance: " ~ std.conv.to!string(this.viewDistance) ~ ", chatMode: " ~ std.conv.to!string(this.chatMode) ~ ", chatColors: " ~ std.conv.to!string(this.chatColors) ~ ", displayedSkinParts: " ~ std.conv.to!string(this.displayedSkinParts) ~ ", mainHand: " ~ std.conv.to!string(this.mainHand) ~ ")";
    }

}

class TabComplete : Java393Packet
{

    enum uint ID = 5;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["transactionId", "text"];

    @Var uint transactionId;
    string text;

    this() pure nothrow @safe @nogc {}

    this(uint transactionId, string text=string.init) pure nothrow @safe @nogc
    {
        this.transactionId = transactionId;
        this.text = text;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        TabComplete ret = new TabComplete();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "TabComplete(transactionId: " ~ std.conv.to!string(this.transactionId) ~ ", text: " ~ std.conv.to!string(this.text) ~ ")";
    }

}

class ConfirmTransaction : Java393Packet
{

    enum uint ID = 6;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["window", "action", "accepted"];

    ubyte window;
    ushort action;
    bool accepted;

    this() pure nothrow @safe @nogc {}

    this(ubyte window, ushort action=ushort.init, bool accepted=bool.init) pure nothrow @safe @nogc
    {
        this.window = window;
        this.action = action;
        this.accepted = accepted;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        ConfirmTransaction ret = new ConfirmTransaction();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "ConfirmTransaction(window: " ~ std.conv.to!string(this.window) ~ ", action: " ~ std.conv.to!string(this.action) ~ ", accepted: " ~ std.conv.to!string(this.accepted) ~ ")";
    }

}

class EnchantItem : Java393Packet
{

    enum uint ID = 7;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["window", "enchantment"];

    ubyte window;
    ubyte enchantment;

    this() pure nothrow @safe @nogc {}

    this(ubyte window, ubyte enchantment=ubyte.init) pure nothrow @safe @nogc
    {
        this.window = window;
        this.enchantment = enchantment;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        EnchantItem ret = new EnchantItem();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "EnchantItem(window: " ~ std.conv.to!string(this.window) ~ ", enchantment: " ~ std.conv.to!string(this.enchantment) ~ ")";
    }

}

class ClickWindow : Java393Packet
{

    enum uint ID = 8;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["window", "slot", "button", "action", "mode", "clickedItem"];

    ubyte window;
    ushort slot;
    ubyte button;
    ushort action;
    @Var uint mode;
    soupply.java393.types.Slot clickedItem;

    this() pure nothrow @safe @nogc {}

    this(ubyte window, ushort slot=ushort.init, ubyte button=ubyte.init, ushort action=ushort.init, uint mode=uint.init, soupply.java393.types.Slot clickedItem=soupply.java393.types.Slot.init) pure nothrow @safe @nogc
    {
        this.window = window;
        this.slot = slot;
        this.button = button;
        this.action = action;
        this.mode = mode;
        this.clickedItem = clickedItem;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        ClickWindow ret = new ClickWindow();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "ClickWindow(window: " ~ std.conv.to!string(this.window) ~ ", slot: " ~ std.conv.to!string(this.slot) ~ ", button: " ~ std.conv.to!string(this.button) ~ ", action: " ~ std.conv.to!string(this.action) ~ ", mode: " ~ std.conv.to!string(this.mode) ~ ", clickedItem: " ~ std.conv.to!string(this.clickedItem) ~ ")";
    }

}

class CloseWindow : Java393Packet
{

    enum uint ID = 9;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["window"];

    ubyte window;

    this() pure nothrow @safe @nogc {}

    this(ubyte window) pure nothrow @safe @nogc
    {
        this.window = window;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        CloseWindow ret = new CloseWindow();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "CloseWindow(window: " ~ std.conv.to!string(this.window) ~ ")";
    }

}

class PluginMessage : Java393Packet
{

    enum uint ID = 10;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["channel", "data"];

    string channel;
    @Bytes ubyte[] data;

    this() pure nothrow @safe @nogc {}

    this(string channel, ubyte[] data=(ubyte[]).init) pure nothrow @safe @nogc
    {
        this.channel = channel;
        this.data = data;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        PluginMessage ret = new PluginMessage();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "PluginMessage(channel: " ~ std.conv.to!string(this.channel) ~ ", data: " ~ std.conv.to!string(this.data) ~ ")";
    }

}

class EditBook : Java393Packet
{

    enum uint ID = 11;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["newBook", "signing"];

    soupply.java393.types.Slot newBook;
    bool signing;

    this() pure nothrow @safe @nogc {}

    this(soupply.java393.types.Slot newBook, bool signing=bool.init) pure nothrow @safe @nogc
    {
        this.newBook = newBook;
        this.signing = signing;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        EditBook ret = new EditBook();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "EditBook(newBook: " ~ std.conv.to!string(this.newBook) ~ ", signing: " ~ std.conv.to!string(this.signing) ~ ")";
    }

}

class QueryEntityNbt : Java393Packet
{

    enum uint ID = 12;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["transactionId", "entityId"];

    @Var uint transactionId;
    @Var uint entityId;

    this() pure nothrow @safe @nogc {}

    this(uint transactionId, uint entityId=uint.init) pure nothrow @safe @nogc
    {
        this.transactionId = transactionId;
        this.entityId = entityId;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        QueryEntityNbt ret = new QueryEntityNbt();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "QueryEntityNbt(transactionId: " ~ std.conv.to!string(this.transactionId) ~ ", entityId: " ~ std.conv.to!string(this.entityId) ~ ")";
    }

}

class UseEntity : Java393Packet
{

    enum uint ID = 13;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // type
    enum uint INTERACT = 0;
    enum uint ATTACK = 1;
    enum uint INTERACT_AT = 2;

    // hand
    enum uint MAIN_HAND = 0;
    enum uint OFF_HAND = 1;

    enum string[] __fields = ["target", "type", "targetPosition", "hand"];

    @Var uint target;
    @Var uint type;
    @Condition("type==2") Vector!(float, "xyz") targetPosition;
    @Condition("type==0||type==2") @Var uint hand;

    this() pure nothrow @safe @nogc {}

    this(uint target, uint type=uint.init, Vector!(float, "xyz") targetPosition=Vector!(float, "xyz").init, uint hand=uint.init) pure nothrow @safe @nogc
    {
        this.target = target;
        this.type = type;
        this.targetPosition = targetPosition;
        this.hand = hand;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        UseEntity ret = new UseEntity();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "UseEntity(target: " ~ std.conv.to!string(this.target) ~ ", type: " ~ std.conv.to!string(this.type) ~ ", targetPosition: " ~ std.conv.to!string(this.targetPosition) ~ ", hand: " ~ std.conv.to!string(this.hand) ~ ")";
    }

}

class KeepAlive : Java393Packet
{

    enum uint ID = 14;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["id"];

    long id;

    this() pure nothrow @safe @nogc {}

    this(long id) pure nothrow @safe @nogc
    {
        this.id = id;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        KeepAlive ret = new KeepAlive();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "KeepAlive(id: " ~ std.conv.to!string(this.id) ~ ")";
    }

}

class Player : Java393Packet
{

    enum uint ID = 15;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["onGround"];

    bool onGround;

    this() pure nothrow @safe @nogc {}

    this(bool onGround) pure nothrow @safe @nogc
    {
        this.onGround = onGround;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        Player ret = new Player();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "Player(onGround: " ~ std.conv.to!string(this.onGround) ~ ")";
    }

}

class PlayerPosition : Java393Packet
{

    enum uint ID = 16;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["position", "onGround"];

    Vector!(double, "xyz") position;
    bool onGround;

    this() pure nothrow @safe @nogc {}

    this(Vector!(double, "xyz") position, bool onGround=bool.init) pure nothrow @safe @nogc
    {
        this.position = position;
        this.onGround = onGround;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        PlayerPosition ret = new PlayerPosition();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "PlayerPosition(position: " ~ std.conv.to!string(this.position) ~ ", onGround: " ~ std.conv.to!string(this.onGround) ~ ")";
    }

}

class PlayerPositionAndLook : Java393Packet
{

    enum uint ID = 17;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["position", "yaw", "pitch", "onGround"];

    Vector!(double, "xyz") position;
    float yaw;
    float pitch;
    bool onGround;

    this() pure nothrow @safe @nogc {}

    this(Vector!(double, "xyz") position, float yaw=float.init, float pitch=float.init, bool onGround=bool.init) pure nothrow @safe @nogc
    {
        this.position = position;
        this.yaw = yaw;
        this.pitch = pitch;
        this.onGround = onGround;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        PlayerPositionAndLook ret = new PlayerPositionAndLook();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "PlayerPositionAndLook(position: " ~ std.conv.to!string(this.position) ~ ", yaw: " ~ std.conv.to!string(this.yaw) ~ ", pitch: " ~ std.conv.to!string(this.pitch) ~ ", onGround: " ~ std.conv.to!string(this.onGround) ~ ")";
    }

}

class PlayerLook : Java393Packet
{

    enum uint ID = 18;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["yaw", "pitch", "onGround"];

    float yaw;
    float pitch;
    bool onGround;

    this() pure nothrow @safe @nogc {}

    this(float yaw, float pitch=float.init, bool onGround=bool.init) pure nothrow @safe @nogc
    {
        this.yaw = yaw;
        this.pitch = pitch;
        this.onGround = onGround;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        PlayerLook ret = new PlayerLook();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "PlayerLook(yaw: " ~ std.conv.to!string(this.yaw) ~ ", pitch: " ~ std.conv.to!string(this.pitch) ~ ", onGround: " ~ std.conv.to!string(this.onGround) ~ ")";
    }

}

class VehicleMove : Java393Packet
{

    enum uint ID = 19;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["position", "yaw", "pitch"];

    Vector!(double, "xyz") position;
    float yaw;
    float pitch;

    this() pure nothrow @safe @nogc {}

    this(Vector!(double, "xyz") position, float yaw=float.init, float pitch=float.init) pure nothrow @safe @nogc
    {
        this.position = position;
        this.yaw = yaw;
        this.pitch = pitch;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        VehicleMove ret = new VehicleMove();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "VehicleMove(position: " ~ std.conv.to!string(this.position) ~ ", yaw: " ~ std.conv.to!string(this.yaw) ~ ", pitch: " ~ std.conv.to!string(this.pitch) ~ ")";
    }

}

class SteerBoat : Java393Packet
{

    enum uint ID = 20;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["rightPaddleTurning", "leftPaddleTurning"];

    bool rightPaddleTurning;
    bool leftPaddleTurning;

    this() pure nothrow @safe @nogc {}

    this(bool rightPaddleTurning, bool leftPaddleTurning=bool.init) pure nothrow @safe @nogc
    {
        this.rightPaddleTurning = rightPaddleTurning;
        this.leftPaddleTurning = leftPaddleTurning;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        SteerBoat ret = new SteerBoat();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "SteerBoat(rightPaddleTurning: " ~ std.conv.to!string(this.rightPaddleTurning) ~ ", leftPaddleTurning: " ~ std.conv.to!string(this.leftPaddleTurning) ~ ")";
    }

}

class PickItem : Java393Packet
{

    enum uint ID = 21;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["slot"];

    @Var uint slot;

    this() pure nothrow @safe @nogc {}

    this(uint slot) pure nothrow @safe @nogc
    {
        this.slot = slot;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        PickItem ret = new PickItem();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "PickItem(slot: " ~ std.conv.to!string(this.slot) ~ ")";
    }

}

class CraftRecipeRequest : Java393Packet
{

    enum uint ID = 22;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["window", "recipe", "makeAll"];

    ubyte window;
    @Var uint recipe;
    bool makeAll;

    this() pure nothrow @safe @nogc {}

    this(ubyte window, uint recipe=uint.init, bool makeAll=bool.init) pure nothrow @safe @nogc
    {
        this.window = window;
        this.recipe = recipe;
        this.makeAll = makeAll;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        CraftRecipeRequest ret = new CraftRecipeRequest();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "CraftRecipeRequest(window: " ~ std.conv.to!string(this.window) ~ ", recipe: " ~ std.conv.to!string(this.recipe) ~ ", makeAll: " ~ std.conv.to!string(this.makeAll) ~ ")";
    }

}

class PlayerAbilities : Java393Packet
{

    enum uint ID = 23;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // flags
    enum ubyte CREATIVE_MODE = 1;
    enum ubyte FLYING = 2;
    enum ubyte ALLOW_FLYING = 4;
    enum ubyte INVINCIBLE = 8;

    enum string[] __fields = ["flags", "flyingSpeed", "walkingSpeed"];

    ubyte flags;
    float flyingSpeed;
    float walkingSpeed;

    this() pure nothrow @safe @nogc {}

    this(ubyte flags, float flyingSpeed=float.init, float walkingSpeed=float.init) pure nothrow @safe @nogc
    {
        this.flags = flags;
        this.flyingSpeed = flyingSpeed;
        this.walkingSpeed = walkingSpeed;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        PlayerAbilities ret = new PlayerAbilities();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "PlayerAbilities(flags: " ~ std.conv.to!string(this.flags) ~ ", flyingSpeed: " ~ std.conv.to!string(this.flyingSpeed) ~ ", walkingSpeed: " ~ std.conv.to!string(this.walkingSpeed) ~ ")";
    }

}

class PlayerDigging : Java393Packet
{

    enum uint ID = 24;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // status
    enum uint START_DIGGING = 0;
    enum uint CANCEL_DIGGING = 1;
    enum uint FINISH_DIGGING = 2;
    enum uint DROP_ITEM_STACK = 3;
    enum uint DROP_ITEM = 4;
    enum uint SHOOT_ARROW = 5;
    enum uint FINISH_EATING = 5;
    enum uint SWAP_ITEM_IN_HAND = 6;

    enum string[] __fields = ["status", "position", "face"];

    @Var uint status;
    ulong position;
    ubyte face;

    this() pure nothrow @safe @nogc {}

    this(uint status, ulong position=ulong.init, ubyte face=ubyte.init) pure nothrow @safe @nogc
    {
        this.status = status;
        this.position = position;
        this.face = face;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        PlayerDigging ret = new PlayerDigging();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "PlayerDigging(status: " ~ std.conv.to!string(this.status) ~ ", position: " ~ std.conv.to!string(this.position) ~ ", face: " ~ std.conv.to!string(this.face) ~ ")";
    }

}

class EntityAction : Java393Packet
{

    enum uint ID = 25;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // action
    enum uint START_SNEAKING = 0;
    enum uint STOP_SNEAKING = 1;
    enum uint LEAVE_BED = 2;
    enum uint START_SPRINTING = 3;
    enum uint STOP_SPRINTING = 4;
    enum uint START_HORSE_JUMP = 5;
    enum uint STOP_HORSE_JUMP = 6;
    enum uint OPEN_HORSE_INVENTORY = 7;
    enum uint START_ELYTRA_FLYING = 8;

    enum string[] __fields = ["entityId", "action", "jumpBoost"];

    @Var uint entityId;
    @Var uint action;
    @Var uint jumpBoost;

    this() pure nothrow @safe @nogc {}

    this(uint entityId, uint action=uint.init, uint jumpBoost=uint.init) pure nothrow @safe @nogc
    {
        this.entityId = entityId;
        this.action = action;
        this.jumpBoost = jumpBoost;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        EntityAction ret = new EntityAction();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "EntityAction(entityId: " ~ std.conv.to!string(this.entityId) ~ ", action: " ~ std.conv.to!string(this.action) ~ ", jumpBoost: " ~ std.conv.to!string(this.jumpBoost) ~ ")";
    }

}

class SteerVehicle : Java393Packet
{

    enum uint ID = 26;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // flags
    enum ubyte JUMP = 1;
    enum ubyte UNMOUNT = 2;

    enum string[] __fields = ["sideways", "forward", "flags"];

    float sideways;
    float forward;
    ubyte flags;

    this() pure nothrow @safe @nogc {}

    this(float sideways, float forward=float.init, ubyte flags=ubyte.init) pure nothrow @safe @nogc
    {
        this.sideways = sideways;
        this.forward = forward;
        this.flags = flags;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        SteerVehicle ret = new SteerVehicle();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "SteerVehicle(sideways: " ~ std.conv.to!string(this.sideways) ~ ", forward: " ~ std.conv.to!string(this.forward) ~ ", flags: " ~ std.conv.to!string(this.flags) ~ ")";
    }

}

class RecipeBookData : Java393Packet
{

    enum uint ID = 27;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["type"];

    @Var uint type;

    this() pure nothrow @safe @nogc {}

    this(uint type) pure nothrow @safe @nogc
    {
        this.type = type;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        RecipeBookData ret = new RecipeBookData();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "RecipeBookData(type: " ~ std.conv.to!string(this.type) ~ ")";
    }

    enum string variantField = "type";

    alias Variants = TypeTuple!(DisplayedRecipe, CraftingBookStatus);

    class DisplayedRecipe : Java393Packet
    {

        enum typeof(type) TYPE = 1;

        enum string[] __fields = ["id"];

        uint id;

        this() pure nothrow @safe @nogc {}

        this(uint id) pure nothrow @safe @nogc
        {
            this.id = id;
        }

        mixin Make;

        override string toString()
        {
            return "RecipeBookData.DisplayedRecipe(id: " ~ std.conv.to!string(this.id) ~ ")";
        }

    }

    class CraftingBookStatus : Java393Packet
    {

        enum typeof(type) TYPE = 2;

        enum string[] __fields = ["craftingRecipeBookOpened", "craftingRecipeFilterActive", "smeltingRecipeBookOpened", "smeltingRecipeFilterActive"];

        bool craftingRecipeBookOpened;
        bool craftingRecipeFilterActive;
        bool smeltingRecipeBookOpened;
        bool smeltingRecipeFilterActive;

        this() pure nothrow @safe @nogc {}

        this(bool craftingRecipeBookOpened, bool craftingRecipeFilterActive=bool.init, bool smeltingRecipeBookOpened=bool.init, bool smeltingRecipeFilterActive=bool.init) pure nothrow @safe @nogc
        {
            this.craftingRecipeBookOpened = craftingRecipeBookOpened;
            this.craftingRecipeFilterActive = craftingRecipeFilterActive;
            this.smeltingRecipeBookOpened = smeltingRecipeBookOpened;
            this.smeltingRecipeFilterActive = smeltingRecipeFilterActive;
        }

        mixin Make;

        override string toString()
        {
            return "RecipeBookData.CraftingBookStatus(craftingRecipeBookOpened: " ~ std.conv.to!string(this.craftingRecipeBookOpened) ~ ", craftingRecipeFilterActive: " ~ std.conv.to!string(this.craftingRecipeFilterActive) ~ ", smeltingRecipeBookOpened: " ~ std.conv.to!string(this.smeltingRecipeBookOpened) ~ ", smeltingRecipeFilterActive: " ~ std.conv.to!string(this.smeltingRecipeFilterActive) ~ ")";
        }

    }

}

class NameItem : Java393Packet
{

    enum uint ID = 28;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["itemName"];

    string itemName;

    this() pure nothrow @safe @nogc {}

    this(string itemName) pure nothrow @safe @nogc
    {
        this.itemName = itemName;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        NameItem ret = new NameItem();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "NameItem(itemName: " ~ std.conv.to!string(this.itemName) ~ ")";
    }

}

class ResourcePackStatus : Java393Packet
{

    enum uint ID = 29;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // result
    enum uint LOADED = 0;
    enum uint DECLINED = 1;
    enum uint FAILED = 2;
    enum uint ACCEPTED = 3;

    enum string[] __fields = ["result"];

    @Var uint result;

    this() pure nothrow @safe @nogc {}

    this(uint result) pure nothrow @safe @nogc
    {
        this.result = result;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        ResourcePackStatus ret = new ResourcePackStatus();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "ResourcePackStatus(result: " ~ std.conv.to!string(this.result) ~ ")";
    }

}

class AdvencementTab : Java393Packet
{

    enum uint ID = 30;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // action
    enum uint OPEN_TAB = 0;
    enum uint CLOSE_SCREEN = 1;

    enum string[] __fields = ["action", "tab"];

    @Var uint action;
    @Condition("action==0") string tab;

    this() pure nothrow @safe @nogc {}

    this(uint action, string tab=string.init) pure nothrow @safe @nogc
    {
        this.action = action;
        this.tab = tab;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        AdvencementTab ret = new AdvencementTab();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "AdvencementTab(action: " ~ std.conv.to!string(this.action) ~ ", tab: " ~ std.conv.to!string(this.tab) ~ ")";
    }

}

class SelectTrade : Java393Packet
{

    enum uint ID = 31;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["selectedSlot"];

    @Var uint selectedSlot;

    this() pure nothrow @safe @nogc {}

    this(uint selectedSlot) pure nothrow @safe @nogc
    {
        this.selectedSlot = selectedSlot;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        SelectTrade ret = new SelectTrade();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "SelectTrade(selectedSlot: " ~ std.conv.to!string(this.selectedSlot) ~ ")";
    }

}

class SetBeaconEffect : Java393Packet
{

    enum uint ID = 32;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["primaryEffect", "secondaryEffect"];

    @Var uint primaryEffect;
    @Var uint secondaryEffect;

    this() pure nothrow @safe @nogc {}

    this(uint primaryEffect, uint secondaryEffect=uint.init) pure nothrow @safe @nogc
    {
        this.primaryEffect = primaryEffect;
        this.secondaryEffect = secondaryEffect;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        SetBeaconEffect ret = new SetBeaconEffect();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "SetBeaconEffect(primaryEffect: " ~ std.conv.to!string(this.primaryEffect) ~ ", secondaryEffect: " ~ std.conv.to!string(this.secondaryEffect) ~ ")";
    }

}

class HeldItemChange : Java393Packet
{

    enum uint ID = 33;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["slot"];

    ushort slot;

    this() pure nothrow @safe @nogc {}

    this(ushort slot) pure nothrow @safe @nogc
    {
        this.slot = slot;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        HeldItemChange ret = new HeldItemChange();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "HeldItemChange(slot: " ~ std.conv.to!string(this.slot) ~ ")";
    }

}

class UpdateCommandBlock : Java393Packet
{

    enum uint ID = 34;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // mode
    enum uint SEQUENCE = 0;
    enum uint AUTO = 1;
    enum uint REDSTONE = 2;

    // flags
    enum ubyte TRACK_OUTPUT = 1;
    enum ubyte CONDITIONAL = 2;
    enum ubyte AUTOMATIC = 4;

    enum string[] __fields = ["location", "command", "mode", "flags"];

    soupply.java393.types.Position location;
    string command;
    @Var uint mode;
    ubyte flags;

    this() pure nothrow @safe @nogc {}

    this(soupply.java393.types.Position location, string command=string.init, uint mode=uint.init, ubyte flags=ubyte.init) pure nothrow @safe @nogc
    {
        this.location = location;
        this.command = command;
        this.mode = mode;
        this.flags = flags;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        UpdateCommandBlock ret = new UpdateCommandBlock();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "UpdateCommandBlock(location: " ~ std.conv.to!string(this.location) ~ ", command: " ~ std.conv.to!string(this.command) ~ ", mode: " ~ std.conv.to!string(this.mode) ~ ", flags: " ~ std.conv.to!string(this.flags) ~ ")";
    }

}

class UpdateCommandBlockMinecart : Java393Packet
{

    enum uint ID = 35;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["entityId", "command", "trackOutput"];

    @Var uint entityId;
    string command;
    bool trackOutput;

    this() pure nothrow @safe @nogc {}

    this(uint entityId, string command=string.init, bool trackOutput=bool.init) pure nothrow @safe @nogc
    {
        this.entityId = entityId;
        this.command = command;
        this.trackOutput = trackOutput;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        UpdateCommandBlockMinecart ret = new UpdateCommandBlockMinecart();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "UpdateCommandBlockMinecart(entityId: " ~ std.conv.to!string(this.entityId) ~ ", command: " ~ std.conv.to!string(this.command) ~ ", trackOutput: " ~ std.conv.to!string(this.trackOutput) ~ ")";
    }

}

class CreativeInventoryAction : Java393Packet
{

    enum uint ID = 36;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["slot", "clickedItem"];

    ushort slot;
    soupply.java393.types.Slot clickedItem;

    this() pure nothrow @safe @nogc {}

    this(ushort slot, soupply.java393.types.Slot clickedItem=soupply.java393.types.Slot.init) pure nothrow @safe @nogc
    {
        this.slot = slot;
        this.clickedItem = clickedItem;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        CreativeInventoryAction ret = new CreativeInventoryAction();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "CreativeInventoryAction(slot: " ~ std.conv.to!string(this.slot) ~ ", clickedItem: " ~ std.conv.to!string(this.clickedItem) ~ ")";
    }

}

class UpdateStructureBlock : Java393Packet
{

    enum uint ID = 37;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // action
    enum uint UPDATE_DATA = 0;
    enum uint SAVE_STRUCTURE = 1;
    enum uint LOAD_STRUCTURE = 2;
    enum uint DETECT_SIZE = 3;

    // mode
    enum uint SAVE = 0;
    enum uint LOAD = 1;
    enum uint CORNER = 2;
    enum uint DATA = 3;

    // mirror
    enum uint NONE = 0;
    enum uint LEFT_RIGHT = 1;
    enum uint FRONT_BACK = 2;

    // rotation
    enum uint CLOCKWISE_90 = 1;
    enum uint CLOCKWISE_180 = 2;
    enum uint COUNTERCLOCKWISE_90 = 3;

    // flags
    enum ubyte IGNORE_ENTITIES = 1;
    enum ubyte SHOW_AIR = 2;
    enum ubyte SHOW_BOUNDING_BOX = 4;

    enum string[] __fields = ["location", "action", "mode", "offset", "size", "mirror", "rotation", "metadata", "integrity", "speed", "flags"];

    soupply.java393.types.Position location;
    @Var uint action;
    @Var uint mode;
    Vector!(byte, "xyz") offset;
    Vector!(ubyte, "xyz") size;
    @Var uint mirror;
    @Var uint rotation;
    string metadata;
    float integrity;
    @Var ulong speed;
    ubyte flags;

    this() pure nothrow @safe @nogc {}

    this(soupply.java393.types.Position location, uint action=uint.init, uint mode=uint.init, Vector!(byte, "xyz") offset=Vector!(byte, "xyz").init, Vector!(ubyte, "xyz") size=Vector!(ubyte, "xyz").init, uint mirror=uint.init, uint rotation=uint.init, string metadata=string.init, float integrity=float.init, ulong speed=ulong.init, ubyte flags=ubyte.init) pure nothrow @safe @nogc
    {
        this.location = location;
        this.action = action;
        this.mode = mode;
        this.offset = offset;
        this.size = size;
        this.mirror = mirror;
        this.rotation = rotation;
        this.metadata = metadata;
        this.integrity = integrity;
        this.speed = speed;
        this.flags = flags;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        UpdateStructureBlock ret = new UpdateStructureBlock();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "UpdateStructureBlock(location: " ~ std.conv.to!string(this.location) ~ ", action: " ~ std.conv.to!string(this.action) ~ ", mode: " ~ std.conv.to!string(this.mode) ~ ", offset: " ~ std.conv.to!string(this.offset) ~ ", size: " ~ std.conv.to!string(this.size) ~ ", mirror: " ~ std.conv.to!string(this.mirror) ~ ", rotation: " ~ std.conv.to!string(this.rotation) ~ ", metadata: " ~ std.conv.to!string(this.metadata) ~ ", integrity: " ~ std.conv.to!string(this.integrity) ~ ", speed: " ~ std.conv.to!string(this.speed) ~ ", flags: " ~ std.conv.to!string(this.flags) ~ ")";
    }

}

class UpdateSign : Java393Packet
{

    enum uint ID = 38;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["position", "lines"];

    ulong position;
    string[4] lines;

    this() pure nothrow @safe @nogc {}

    this(ulong position, string[4] lines=(string[4]).init) pure nothrow @safe @nogc
    {
        this.position = position;
        this.lines = lines;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        UpdateSign ret = new UpdateSign();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "UpdateSign(position: " ~ std.conv.to!string(this.position) ~ ", lines: " ~ std.conv.to!string(this.lines) ~ ")";
    }

}

class Animation : Java393Packet
{

    enum uint ID = 39;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // hand
    enum uint MAIN_HAND = 0;
    enum uint OFF_HAND = 1;

    enum string[] __fields = ["hand"];

    @Var uint hand;

    this() pure nothrow @safe @nogc {}

    this(uint hand) pure nothrow @safe @nogc
    {
        this.hand = hand;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        Animation ret = new Animation();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "Animation(hand: " ~ std.conv.to!string(this.hand) ~ ")";
    }

}

class Spectate : Java393Packet
{

    enum uint ID = 40;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    enum string[] __fields = ["player"];

    UUID player;

    this() pure nothrow @safe @nogc {}

    this(UUID player) pure nothrow @safe @nogc
    {
        this.player = player;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        Spectate ret = new Spectate();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "Spectate(player: " ~ std.conv.to!string(this.player) ~ ")";
    }

}

class PlayerBlockPlacement : Java393Packet
{

    enum uint ID = 41;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // hand
    enum uint MAIN_HAND = 0;
    enum uint OFF_HAND = 1;

    enum string[] __fields = ["position", "face", "hand", "cursorPosition"];

    ulong position;
    @Var uint face;
    @Var uint hand;
    Vector!(float, "xyz") cursorPosition;

    this() pure nothrow @safe @nogc {}

    this(ulong position, uint face=uint.init, uint hand=uint.init, Vector!(float, "xyz") cursorPosition=Vector!(float, "xyz").init) pure nothrow @safe @nogc
    {
        this.position = position;
        this.face = face;
        this.hand = hand;
        this.cursorPosition = cursorPosition;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        PlayerBlockPlacement ret = new PlayerBlockPlacement();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "PlayerBlockPlacement(position: " ~ std.conv.to!string(this.position) ~ ", face: " ~ std.conv.to!string(this.face) ~ ", hand: " ~ std.conv.to!string(this.hand) ~ ", cursorPosition: " ~ std.conv.to!string(this.cursorPosition) ~ ")";
    }

}

class UseItem : Java393Packet
{

    enum uint ID = 42;

    enum bool CLIENTBOUND = false;
    enum bool SERVERBOUND = true;

    // hand
    enum uint MAIN_HAND = 0;
    enum uint OFF_HAND = 1;

    enum string[] __fields = ["hand"];

    @Var uint hand;

    this() pure nothrow @safe @nogc {}

    this(uint hand) pure nothrow @safe @nogc
    {
        this.hand = hand;
    }

    mixin Make;

    public static typeof(this) fromBuffer(ubyte[] buffer)
    {
        UseItem ret = new UseItem();
        ret.autoDecode(buffer);
        return ret;
    }

    override string toString()
    {
        return "UseItem(hand: " ~ std.conv.to!string(this.hand) ~ ")";
    }

}
