/*
 * This file has been automatically generated by Soupply and released un the MIT license.
 */
module soupply.protocol.java340.packet;

import packetmaker;

alias Java340Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
