/*
 * This file has been automatically generated by Soupply and released un the MIT license.
 */
module soupply.protocol.pocket100.packet;

import packetmaker;

alias Pocket100Packet = PacketImpl!(Endian.bigEndian, ubyte, varuint);
