/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.bedrock.packet;

public import soupply.bedrock137.packet;

alias BedrockPacket = Bedrock137Packet;
