/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 * Generated from data/test0.xml
 */
module soupply.test0.types;

static import std.conv;
import packetmaker;
import packetmaker.maker : EndianType, writeLength, readLength;

import soupply.util : Vector, UUID;
import soupply.test0.metadata;
