/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.protocol.pocket101.packet;

import packetmaker;

alias Pocket101Packet = PacketImpl!(Endian.bigEndian, ubyte, varuint);
