/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.pocket105.packet;

import packetmaker;

alias Pocket105Packet = PacketImpl!(Endian.bigEndian, ubyte, varuint);
