/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.protocol.pocket102.packet;

import packetmaker;

alias Pocket102Packet = PacketImpl!(Endian.bigEndian, ubyte, varuint);
