/*
 * This file has been automatically generated by Soupply and released un the MIT license.
 */
module soupply.protocol.bedrock150.packet;

import packetmaker;

alias Bedrock150Packet = PacketImpl!(Endian.littleEndian, varuint, varuint);
