/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java210.protocol;

public import soupply.java210.protocol.clientbound;
public import soupply.java210.protocol.login;
public import soupply.java210.protocol.serverbound;
public import soupply.java210.protocol.status;
