/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.protocol.java316.packet;

import packetmaker;

alias Java316Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
