/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java338.protocol;

public import soupply.java338.protocol.clientbound;
public import soupply.java338.protocol.login;
public import soupply.java338.protocol.serverbound;
public import soupply.java338.protocol.status;
