/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java340;

public import soupply.java340.packet;
public import soupply.java340.types;
public import soupply.java340.protocol;
public import soupply.java340.metadata;
