/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java340.packet;

import xpacket;

alias Java340Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
