/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.test0.packet;

import xpacket;

alias Test0Packet = PacketImpl!(Endian.bigEndian, ubyte, varuint);
