/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 * Generated from data/test0.xml
 */
module soupply.test0.types;

static import std.conv;
import xpacket;

import xserial.serial : EndianType, serializeLength, deserializeLength;

import xbuffer.memory : xalloc, xfree;

import soupply.util;
import soupply.test0.metadata;
