/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java315;

public import soupply.java315.packet;
public import soupply.java315.types;
public import soupply.java315.protocol;
public import soupply.java315.metadata;
