/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.protocol.java210.packet;

import packetmaker;

alias Java210Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
