/*
 * This file has been automatically generated by Soupply and released un the MIT license.
 */
module soupply.protocol.java335.packet;

import packetmaker;

alias Java335Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
