/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.bedrock282.packet;

import xpacket;

alias Bedrock282Packet = PacketImpl!(Endian.littleEndian, varuint, varuint);
