/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.protocol.bedrock137.packet;

import packetmaker;

alias Bedrock137Packet = PacketImpl!(Endian.littleEndian, varuint, varuint);
