/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java315.protocol;

public import soupply.java315.protocol.clientbound;
public import soupply.java315.protocol.login;
public import soupply.java315.protocol.serverbound;
public import soupply.java315.protocol.status;
