/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.bedrock261.packet;

import xpacket;

import soupply.util : Pad;

alias Bedrock261Packet = Pad!(2, PacketImpl!(Endian.littleEndian, varuint, varuint));
