/*
 * This file has been automatically generated by Soupply and released un the MIT license.
 */
module soupply.protocol.pocket105.packet;

import packetmaker;

alias Pocket105Packet = PacketImpl!(Endian.bigEndian, ubyte, varuint);
