/*
 * This file has been automatically generated by Soupply and released un the MIT license.
 */
module soupply.protocol.bedrock141.packet;

import packetmaker;

alias Bedrock141Packet = PacketImpl!(Endian.littleEndian, varuint, varuint);
