/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.bedrock201.packet;

import packetmaker;

import soupply.util : Pad;

alias Bedrock201Packet = Pad!(2, PacketImpl!(Endian.littleEndian, varuint, varuint));
