/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply;

public import soupply.bedrock;
public import soupply.bedrock137;
public import soupply.bedrock141;
public import soupply.bedrock150;
public import soupply.bedrock160;
public import soupply.bedrock201;
public import soupply.bedrock261;
public import soupply.java;
public import soupply.java210;
public import soupply.java315;
public import soupply.java316;
public import soupply.java335;
public import soupply.java338;
public import soupply.java340;
public import soupply.util;
