/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.protocol.bedrock160.packet;

import packetmaker;

alias Bedrock160Packet = PacketImpl!(Endian.littleEndian, varuint, varuint);
