/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java316.packet;

import xpacket;

alias Java316Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
