/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java315.packet;

import xpacket;

alias Java315Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
