/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java338.packet;

import xpacket;

alias Java338Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
