/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java335.packet;

import packetmaker;

alias Java335Packet = PacketImpl!(Endian.bigEndian, varuint, varuint);
