/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.protocol.bedrock201.packet;

import packetmaker;

alias Bedrock201Packet = PacketImpl!(Endian.littleEndian, varuint, varuint);
