/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java.packet;

public import soupply.java340.packet;

alias JavaPacket = Java340Packet;
