/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java.packet;

public import soupply.java210.packet;

alias JavaPacket = Java210Packet;
