/*
 * This file has been automatically generated by Soupply and released under the MIT license.
 */
module soupply.java316.protocol;

public import soupply.java316.protocol.clientbound;
public import soupply.java316.protocol.login;
public import soupply.java316.protocol.serverbound;
public import soupply.java316.protocol.status;
